== Резюме
Долгинин Максим Сергеевич


//[horizontal]
e-mail:: maksim@dolginin.ru
Телефон:: +7 923 1917748

=== Специализация и профессиональные навыки
Комплексное обеспечение безопасности автоматизированных систем, в том числе АСУ ТП, согласно требованиям руководящих документов ФСТЭК, ФСБ и международным стандартам информационной безопасности.

Обеспечение полного цикла защиты персональных данных государственной и коммерческой организации.

Организация процесса продаж услуг по защите информации и средств защиты информации (в том числе средств криптографической защиты и услуг удостоверяющего центра).

Лицензирование организации по линиям ФСТЭК и ФСБ в части защиты конфиденциальной информации:

. Подготовка документов по лицензированию деятельности в области криптографической защиты информации (три лицензии ФСБ плюс разработка СКЗИ);
. Подготовка  документов по лицензированию в области технической защиты конфиденциальной информации (лицензии ФСТЭК на ТЗКИ и разработку СЗИ).

Организация работы Удостоверяющего центра в соответствии с законодательством РФ:

. Разработка нормативно-распорядительной документации удостоверяющего центра;
. Регистрация УЦ в уполномоченном федеральном органе, опыт аккредитации УЦ в различных организациях;
. Опыт администрирования удостоверяющих центров.

=== ОПЫТ РАБОТЫ

==== ООО «Самара криптосервис» г. Самара

===== Специалист отдела информационной безопасности в период с 2003 по 2005 годы.

Обязанности::
Администрирование удостоверяющего центра, заключение договоров на услуги УЦ, установка СКЗИ ViPNet, подготовка документов на лицензии ФСБ, взаимодействие с заказчиками.

==== ООО «Открытый код» г. Самара ,(www.o-code.ru)

===== Начальник отдела информационной безопасности в период с 2005 по 2011 годы

Обязанности::
* Организация процессов продаж СКЗИ и СЗИ, услуг УЦ;
* Организация работы УЦ;
* Подготовка документов на получение лицензий ФСБ, ФСТЭК;
* Организация аттестации ЗП и АС;
* Взаимодействие с заказчиками, консультирование в области защиты конфиденциальной информации и персональных данных (разработка документации, консультации по выбору средств защиты информации, составление технических заданий на систему защиты информации);
* Организация процессов внедрения систем защиты информации (ЗАГС Самарской области, Министерство здравоохранения и социального развития Самарской области, инспекция Гостехнадзора Самарской области, Управление Росреестра по Самарской области и др…);
* Составление для заказчика технических заданий для размещения на сайтах организаторов торгов;
* Выступление на семинарах и выставках с докладами на тему защиты информации.

==== ЗАО «ЛЕТА» представительство в г. Самара (www.leta.ru)

===== Руководитель проектов в период с 2011 по 2012 годы

Обязанности::
* Взаимодействие с заказчиками, консультирование в области защиты конфиденциальной информации и персональных данных (разработка документации, консультации по выбору средств защиты информации, составление технических заданий на системы защиты информации);
* Поддержка продаж услуг и решений по обеспечению информационной безопасности и соответствия требованиям:
** Защита персональных данных
** Обеспечение соответствия требованиям СТО БР ИББС
** Защита банкоматов и критичных систем
** Построение систем противодействия утечке конфиденциальной информации (DLP)
** Построение системы контроля устройств ввода-вывода информации
** Построение корпоративной системы защиты каналов связи (VPN)
** Построение корпоративной инфраструктуры открытых ключей – PKI
** Построение корпоративной системы межсетевого экранирования и др….
* Участие в реализации проектов (разработка организационно-распорядительной и технической документации по проекту, куратор проекта со стороны исполнителя):
** Защита персональных данных
** Защита банкоматов и критичных систем
** Построение корпоративной системы защиты каналов связи (VPN)
** Построение корпоративной инфраструктуры открытых ключей – PKI
* Организация процесса логистики, взаимодействие с вендорами и дистрибьюторами при закупке и продаже продуктов и решений в области информационной безопасности.

===== Руководитель представительства ЗАО "ЛЕТА" в ПФО в период с 2013 по 2014 годы
Обязанности::
* Осуществление общего руководства филиалом.
* Поддержка продаж услуг и решений в области информационной безопасности в части подготовки коммерческих предложений, технических заданий и защиты. Переговоры с заказчиками, проведение презентаций предлагаемых решений.
* Руководство и реализация проектов по защите информации.

.Ниже приведены основные проекты, реализованные в 2013 году под моим руководством и с моим участием в качестве аналитика:
. Защита персональных данных в Государственной жилищной инспекции Самарской области (www.gzhi-samara.ru), а так же защита информации в системе «Электронное ЖКХ». В рамках этого проекта проведено обследование информационных систем заказчика с целью выявления процессов обработки персональных данных, разработана необходимая организационно-распорядительная документация и внедрена система защиты персональных данных. Для организации защищенного доступа к системе «Электронное ЖКХ» внедрен программно-аппаратный комплекс StoneGate SSL.
. Защита персональных данных в Медицинской компании ИДК (www.mc-idk.ru). В рамках этого проекта проведено обследование информационных систем заказчика с целью выявления процессов обработки персональных данных, разработана необходимая организационно-распорядительная документация и внедрена система защиты персональных данных.
. Защита персональных данных в ЗАО «Самарская сетевая компания» (www.ssk63.ru). В рамках этого проекта проведено обследование информационных систем заказчика с целью выявления процессов обработки персональных данных, разработана необходимая организационно-распорядительная документация и внедрена система защиты персональных данных.
. Организация защищенного канала передачи данных для ЗАО «Новокуйбышевская нефтехимическая компания» (www.sanors.ru) на базе StoneGate FW/VPN. В рамках проекта в сжатые стройки были поставлен и внедрен программно-аппаратный комплекс StoneGate FW/VPN для связи Новокуйбышевской и Московской площадок предприятия.
. Обследование информационной системы и разработка документации для внедрения DLP системы «Контур информационной безопасности SearchInform» для ФГУП «ГНПРКЦ «ЦСКБ-Прогресс» (www.samspace.ru). Внедрение DLP системы осуществлял Энвижн. В наши задачи входило проведение обследования информационной системы заказчика и разработка необходимой для внедрения документации: технический проект, регламент использования внешних носителей информации, программа и методика испытаний.
. Защита банкоматов для ОАО Банк АВБ. В рамках проекта построена защищенная сеть передачи данных в сети банкоматов Банка АВБ, а так же внедрен программный комплекс McAfee Integrity Control, блокирующий несанкционированные приложения и изменения на банкоматах банка.
. Разработка типового комплекта документации по защите персональных данных в многофункциональных центрах оказания государственных и муниципальных услуг Самарской области и успешная реализация муниципальных контрактов на соответствующие работы у конечных заказчиков.

==== ООО «АйТи Таск» (www.it-task.ru)

===== Руководитель проектов в период с 2014 г. – по настоящее время

Обязанности::
* Поддержка продаж услуг и решений в области информационной безопасности в части подготовки коммерческих предложений, технических заданий и защиты. Переговоры с заказчиками, проведение презентаций предлагаемых решений.
* Руководство и реализация проектов по защите информации.
* Но ниже приведены основные направления работы в компании:
. Реализация проектов по защите персональных данных в соответствии с требованиями законодательства РФ:
.. Проведение обследования процессов обработки ПДн;
.. Описание и классификация информационных систем персональных данных;
.. Моделирование угроз безопасности ПДн;
.. Проектирование систем защиты информации ИСПДн.
. Реализация проектов по защите автоматизированных систем управления технологическими процессами в соответствии с требованиями законодательства РФ
.. Проведение обследования АСУ ТП;
.. Описание и классификация АСУ ТП;
.. Формирование требований к системе защиты информации, обрабатываемой в АСУ ТП;
.. Проектирование систем защиты информации, обрабатываемой в АСУ ТП.

=== Образование и повышение квалификации

.Университет Российской академии образования  г. Самара
* заканчиваю в настоящее время
* Специальность: менеджмент

.Самарский государственный университет     г. Самара
* Повышение квалификации по курсу «Защита персональных данных»

.Учебный центр ЦБИ      г. Королев
* Повышение квалификации по курсу «Техническая защита конфиденциальной информации»

.ОАО «Инфотекс»    г. Москва
* Администрирование системы защиты информации ViPNet

.ООО «Конфидент»     г. Санкт-Петербург
* Администрирование системы защиты информации от несанкционированного доступа Dallas Lock 7.5

.Учебный центр «Академия Информационных Систем» г. Москва
* Администрирование StoneGate SMC
* Администрирование StoneGate FW/VPN
* Администрирование StoneGate SSL

=== ВЛАДЕНИЕ ЯЗЫКАМИ
* Русский – родной язык;
* Английский – чтение и перевод со словарем.

